### ISSUE TITLE
Issues with Safari in 10.13.3

### ISSUE THREAD

**Issue by quartz-dk** [plan44/localSites#5]
Hi

I was very happy, when i discovered LocalSites, as I was extremely unhappy, that Bonjour for some reason was removed from Safari.

The utility was downloaded from the AppStore, but seems NOT to be working.

The utility discovers and lists the Local devices correctly with name and a local ID, but is for some odd reason not able to connect to the device via the browser. 

Example: My printer - Samsung ML-2850 (SEC00159970D708) is located correctly, but when selected, the site "http://sec00159970d708.local" is called via Safari it stops there and the device is not accessed.

If i try to access the device via it's normal IP address, no problem. 
When i ping with the command "ping sec00159970d708.local" the address is resolved correctly and the printer responds to the ping command. 

If the "sec00159970d708.local" or "http://sec00159970d708.local" is inserted in Firefox or Chrome, the Printer is accessed correctly. Also when called via the key-combination.

However neither "sec00159970d708.local" nor "http://sec00159970d708.local" in the Safari browser works (history cleaning does not help either), i get no connection. Calling via the key combination or leaving it to select the default browser (Safari) yields the same result.

In fewer words: "localSites" works like a peach with Firefox and Chrome, but is a NoGo with Safari.

Any suggestions?

**Comment by plan44** [comment]
Hi,

> On 13 Mar 2018, at 10:43, quartz-dk <notifications@github.com> wrote:
> I was very happy, when i discovered LocalSites, as I was extremely unhappy, that Bonjour for some reason was removed from Safari.
> 
> The utility was downloaded from the AppStore, but seems NOT to be working.
> 
> The utility discovers and lists the Local devices correctly with name and a local ID, but is for some odd reason not able to connect to the device via the browser.
> 
> Example: My printer - Samsung ML-2850 (SEC00159970D708) is located correctly, but when selected, the site "http://sec00159970d708.local" is called via Safari it stops there and the device is not accessed.
> 
> If i try to access the device via it's normal IP address, no problem.
> When i ping with the command "ping sec00159970d708.local" the address is resolved correctly and the printer responds to the ping command.
> 
> If the "sec00159970d708.local" or "http://sec00159970d708.local" is inserted in Firefox or Chrome, the Printer is accessed correctly. Also when called via the key-combination.
> 
> However neither "sec00159970d708.local" nor "http://sec00159970d708.local" in the Safari browser works (history cleaning does not help either), i get no connection. Calling via the key combination or leaving it to select the default browser (Safari) yields the same result.
> 
> In fewer words: "localSites" works like a peach with Firefox and Chrome, but is a NoGo with Safari.
> 
> Any suggestions?

Hmm, that's really strange - in particular because I use LocalSites many times every day in Safari myself without any problem.
I don't have a Samsung printer right here (I might have one I can test later this week), but right now 10 different devices in my office net that I can all browse via LocalSites+Safari (11.0.3 (13604.5.6))

Does this affect all of your devices, or only some?

If possible, can you please do the following:

In a terminal, enter

  dns-sd -B _http

This should essentially show the same list as the LocalSites menu does.
Hit ^C to exit the utility.

Now, for one of the devices you know for sure it does NOT work with LocalSites+Safari, enter

  dns-sd -L 'name exactly as shown under "Instance Name" above' _http

You should get a line saying "...can be reached at xyz.local.:80"

Finally, enter

  dns-sd -G v4v6 xyz.local.

With xyz being the name as returned in the "...can be reached at..." line above.

Please cut & paste the terminal text into an email to be - so maybe I ca spot a difference between your case and mine.

BTW: do you have a IPv6 enabled local network?

Best Regards,

Lukas

**Comment by quartz-dk** [comment]
Hi Lukas

Thank you for your very swift answer :-)

I have tried your suggestions and it has all worked and the last bit gave me the correct IP (i do not have IP V6 enabled).

As you suggested, i have attached the bits from the commandline prompt:

Last login: Tue Mar 13 11:08:57 on console
Kurts-iMac-2:~ kurtnielsen$ dns-sd -B _http
Browsing for _http._tcp
DATE: ---Tue 13 Mar 2018---
13:29:20.447  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
13:29:21.609  Add        2   7 local.               _http._tcp.          Samsung ML-2850 Series (SEC00159970D708)
13:29:21.887  Add        2   8 local.               _http._tcp.          Samsung ML-2850 Series (SEC00159970D708)
dns-sd -L 'Samsung ML-2850 Series (SEC00159970D708)'
^C
Kurts-iMac-2:~ kurtnielsen$ dns-sd -L 'Samsung ML-2850 Series (SEC00159970D708)'_http
dns-sd -E                              (Enumerate recommended registration domains)
dns-sd -F                                  (Enumerate recommended browsing domains)
dns-sd -R <Name> <Type> <Domain> <Port> [<TXT>...]             (Register a service)
dns-sd -B        <Type> <Domain>                     (Browse for service instances)
dns-sd -L <Name> <Type> <Domain>                       (Resolve a service instance)
dns-sd -Q <name> <rrtype> <rrclass>             (Generic query for any record type)
dns-sd -Z        <Type> <Domain>               (Output results in Zone File format)
dns-sd -G     v4/v6/v4v6 <name>              (Get address information for hostname)
dns-sd -H                                   (Print usage for complete command list)
dns-sd -V                (Get version of currently running daemon / system service)
Kurts-iMac-2:~ kurtnielsen$ dns-sd -L 'Samsung ML-2850 Series (SEC00159970D708)' _http
Lookup Samsung ML-2850 Series (SEC00159970D708)._http._tcp.local
DATE: ---Tue 13 Mar 2018---
13:32:20.490  ...STARTING...
13:32:20.491  Samsung\032ML-2850\032Series\032(SEC00159970D708)._http._tcp.local. can be reached at SEC00159970D708.local.:80 (interface 7) Flags: 1
13:32:20.491  Samsung\032ML-2850\032Series\032(SEC00159970D708)._http._tcp.local. can be reached at SEC00159970D708.local.:80 (interface 8)
dns-sd -G 'Samsung ML-2850 Series (SEC00159970D708)'.local                     
^C
Kurts-iMac-2:~ kurtnielsen$ dns-sd -G v4v6 SEC00159970D708.local
DATE: ---Tue 13 Mar 2018---
13:40:19.235  ...STARTING...
Timestamp     A/R Flags if Hostname                               Address                                      TTL
13:40:19.236  Add     3  7 SEC00159970D708.local.                 192.168.1.100                                7200
13:40:19.237  Add     2  8 SEC00159970D708.local.                 192.168.1.100                                7200

If the hostname is handed to Safari, it simply hangs
If the IP address is hand to Safari, I get the Printer web interface 

I have noticed this behaviour on a Brand-new iMac as well last week

Thank you for your help

Best regards 

Kurt

**Comment by plan44** [comment]
Hi Kurt,

I could test with a Samsung printer (CLX-3305) at home and it works perfectly via LocalSites and Safari.

Something must be special in your networking setup.

I don't really understand why dns.sd -L outputs two seemingly identical paths for your printer. Doing the exact same sequence of commands in my terminal only results in a single "...can be reached at" line.

You say:
> If the hostname is handed to Safari, it simply hangs

That's exactly what LocalSites does - it just hands the hostname (plus port number) to the selected browser. It does not resolve the IP address itself, because a hostname should be in the URL field of the browser, not a fixed IP address.

The experiment shows that something is weird with Safari's local host name resolution in your network, and it's not directly related to LocalSites, but happens with dns-sd standard tool as well.

One thing I could imagine that could be the problem is that there *is* some confusion (rfc specs vs. reality) about how to handle the "local" vs "local." domains. Altough strictly speaking all domain names that are absolute should end in a dot, almost never the trailing dot is actually present (nobody enters "google.com." as a URL, although that would be correct). But without the dot, the actual meaning is that the domain specification could be relative to a local domain. For "local" (without dot), that could mean a subdomain called "local" in a local default domain, such as "local.in.my.private.network.". Only "local." strictly means a root domain called "local". Unfortunately, URLs passed to browsers with trailing dots, together with port numbers, often don't work. That's why localSites does not pass the trailing dot.

Now maybe you have a network setup that actually defines a local domain, such that "local" does not actually resolve to the bonjour devices? At least not with the method Safari uses (vs. Mozilla and Chrome...).

What's the output of

  dns-sd -F

in your network?

Lukas

**Comment by quartz-dk** [comment]
Hi Lukas

Sorry for not being answering - i have problems with my back and was down for a while (try not to get old - just a thought).

If I give the "dns-sd -F", I get (after a lot of waiting) - nothing.

However, more interesting - today everything seems to work in Safari. I have not to my knowledge changed anything in the setup of my machines (macOS is not allowed to do automatic updates, neither is any of my networkdevices devices), the only introduced change is, that i had my backupserver switched on.

Last login: Wed Mar 21 10:22:47 on ttys000
Kurts-iMac-2:~ kurtnielsen$ dns-sd -B _http
Browsing for _http._tcp
DATE: ---Wed 21 Mar 2018---
10:33:35.932  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
10:33:35.933  Add        3   7 local.               _http._tcp.          Qube412
10:33:35.933  Add        3   8 local.               _http._tcp.          Qube412
10:33:35.933  Add        3   7 local.               _http._tcp.          Samsung ML-2850 Series (SEC00159970D708)
10:33:35.933  Add        2   8 local.               _http._tcp.          Samsung ML-2850 Series (SEC00159970D708)


The "dns-sd -F" yields the following result:

Kurts-iMac-2:~ kurtnielsen$ dns-sd -F
Looking for recommended browsing domains:
DATE: ---Wed 21 Mar 2018---
10:22:50.017  ...STARTING...
Timestamp     Recommended Browsing domain
10:22:50.018  Added                          local

[No output]

I will try to investigate a little more and will be back with more information.

Thank you for time time Lukas - it is highly appreciated!
